-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.address
(
    id serial NOT NULL,
    street character varying COLLATE pg_catalog."default" NOT NULL,
    postal_code integer NOT NULL,
    CONSTRAINT address_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.admin_action_log
(
    id serial NOT NULL,
    admin_user_id integer NOT NULL,
    action character varying COLLATE pg_catalog."default" NOT NULL,
    target_table character varying COLLATE pg_catalog."default" NOT NULL,
    target_id integer,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT admin_action_log_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.discount
(
    id serial NOT NULL,
    type character varying COLLATE pg_catalog."default" NOT NULL,
    value numeric(10, 2) NOT NULL,
    active boolean NOT NULL DEFAULT true,
    CONSTRAINT discount_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.inventory
(
    item_id integer NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (item_id)
    );

CREATE TABLE IF NOT EXISTS public.item
(
    id serial NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    base_price numeric(10, 2) NOT NULL,
    category_id integer NOT NULL,
    supplier_id integer NOT NULL,
    CONSTRAINT item_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.item_category
(
    id serial NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT item_category_pkey PRIMARY KEY (id),
    CONSTRAINT item_category_name_key UNIQUE (name)
    );

CREATE TABLE IF NOT EXISTS public.item_discount
(
    item_id integer NOT NULL,
    discount_id integer NOT NULL,
    CONSTRAINT item_discount_pkey PRIMARY KEY (item_id, discount_id)
    );

CREATE TABLE IF NOT EXISTS public.item_stamp
(
    item_id integer NOT NULL,
    stamp_id integer NOT NULL,
    CONSTRAINT item_stamp_pkey PRIMARY KEY (item_id, stamp_id)
    );

CREATE TABLE IF NOT EXISTS public."order"
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    address_id integer NOT NULL,
    status character varying COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    completed_at timestamp with time zone,
                               CONSTRAINT order_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.order_item
(
    order_id integer NOT NULL,
    item_id integer NOT NULL,
    quantity integer NOT NULL,
    price_at_purchase numeric(10, 2) NOT NULL,
    CONSTRAINT order_item_pkey PRIMARY KEY (order_id, item_id)
    );

CREATE TABLE IF NOT EXISTS public.postal_code
(
    postal_code integer NOT NULL,
    city character varying COLLATE pg_catalog."default" NOT NULL,
    country character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT postal_code_pkey PRIMARY KEY (postal_code)
    );

CREATE TABLE IF NOT EXISTS public.quality_check
(
    id serial NOT NULL,
    item_id integer NOT NULL,
    approved boolean NOT NULL,
    checked_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT quality_check_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.stamp
(
    id serial NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT stamp_pkey PRIMARY KEY (id),
    CONSTRAINT stamp_name_key UNIQUE (name)
    );

CREATE TABLE IF NOT EXISTS public.stock_change
(
    id serial NOT NULL,
    item_id integer NOT NULL,
    supplier_id integer,
    delta integer NOT NULL,
    reason character varying COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT stock_change_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.supplier
(
    id serial NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    contact_email character varying COLLATE pg_catalog."default",
    CONSTRAINT supplier_pkey PRIMARY KEY (id),
    CONSTRAINT supplier_name_key UNIQUE (name)
    );

CREATE TABLE IF NOT EXISTS public.transaction
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    amount numeric(10, 2) NOT NULL,
    type character varying COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT transaction_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public."user"
(
    id serial NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    email character varying COLLATE pg_catalog."default" NOT NULL,
    wallet numeric(10, 2) NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    role character varying NOT NULL DEFAULT
    CONSTRAINT user_pkey PRIMARY KEY (id),
    CONSTRAINT user_email_key UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS public."userAuth"
(
    user_id integer NOT NULL,
    username character varying COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "userAuth_pkey" PRIMARY KEY (user_id),
    CONSTRAINT "userAuth_username_key" UNIQUE (username)
    );

ALTER TABLE IF EXISTS public.address
    ADD CONSTRAINT fk_address_postal_code FOREIGN KEY (postal_code)
    REFERENCES public.postal_code (postal_code) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.admin_action_log
    ADD CONSTRAINT fk_adminlog_user FOREIGN KEY (admin_user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT fk_inventory_item FOREIGN KEY (item_id)
    REFERENCES public.item (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS inventory_pkey
    ON public.inventory(item_id);


ALTER TABLE IF EXISTS public.item
    ADD CONSTRAINT fk_item_category FOREIGN KEY (category_id)
    REFERENCES public.item_category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.item
    ADD CONSTRAINT fk_item_supplier FOREIGN KEY (supplier_id)
    REFERENCES public.supplier (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.item_discount
    ADD CONSTRAINT fk_itemdiscount_discount FOREIGN KEY (discount_id)
    REFERENCES public.discount (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.item_discount
    ADD CONSTRAINT fk_itemdiscount_item FOREIGN KEY (item_id)
    REFERENCES public.item (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.item_stamp
    ADD CONSTRAINT fk_itemstamp_item FOREIGN KEY (item_id)
    REFERENCES public.item (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.item_stamp
    ADD CONSTRAINT fk_itemstamp_stamp FOREIGN KEY (stamp_id)
    REFERENCES public.stamp (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."order"
    ADD CONSTRAINT fk_order_address FOREIGN KEY (address_id)
    REFERENCES public.address (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."order"
    ADD CONSTRAINT fk_order_user FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_item
    ADD CONSTRAINT fk_orderitem_item FOREIGN KEY (item_id)
    REFERENCES public.item (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_item
    ADD CONSTRAINT fk_orderitem_order FOREIGN KEY (order_id)
    REFERENCES public."order" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.quality_check
    ADD CONSTRAINT fk_qualitycheck_item FOREIGN KEY (item_id)
    REFERENCES public.item (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.stock_change
    ADD CONSTRAINT fk_stockchange_item FOREIGN KEY (item_id)
    REFERENCES public.item (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.stock_change
    ADD CONSTRAINT fk_stockchange_supplier FOREIGN KEY (supplier_id)
    REFERENCES public.supplier (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transaction
    ADD CONSTRAINT fk_transaction_user FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."userAuth"
    ADD CONSTRAINT fk_userauth_user FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "userAuth_pkey"
    ON public."userAuth"(user_id);

END;